# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.IntegerField(unique=True)),
                ('version', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('screen_shot', models.ImageField(null=True, upload_to=home.models.screen_shot_path)),
                ('resource_file', models.FileField(null=True, upload_to=home.models.resource_file_path)),
                ('is_audit', models.BooleanField(default=False)),
                ('is_pass', models.BooleanField(default=False)),
                ('reason', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Art')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('can_admin', 'can admin'), ('can_developer', 'can developer'), ('can_plan', 'can plan'), ('can_art', 'can art')),
            },
        ),
        migrations.CreateModel(
            name='GroupToTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('sort', models.IntegerField()),
                ('is_select', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
            ],
        ),
        migrations.AddField(
            model_name='grouptotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tag'),
        ),
        migrations.AddField(
            model_name='artinfo',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tag'),
        ),
        migrations.AddField(
            model_name='art',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group'),
        ),
        migrations.AddField(
            model_name='art',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
