# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagorder',
            name='is_select',
        ),
        migrations.AlterField(
            model_name='art',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
